
version: '1.0.{build}'
environment:
 CODECOV_IO_TOKEN:
    secure: dGZ4I/2UkD2OYCkSkIn7VBEOtEy/Jd4VbaOBhZ+xTa28CbrkWES1ERffPl+cWd0V
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./MeMBank.Service/MemBank.Service.csproj --verbosity m
build_script:
  - cmd: dotnet build ./MeMBank.Service/MemBank.Service.csproj
after_build:
  # For once the build has completed
test_script:
  - OpenCover.Console.exe -target:"dotnet.exe" -targetargs:" test " -register:user -oldStyle -output:OpenCoverResults.xml
after_test:
  - ps: |
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "OpenCoverResults.xml" -t $env:CODECOV_IO_TOKEN
on_finish :
  # any cleanup in here
deploy: off